- name: Configure container runtime
  include_role:
    name: common/docker_base
  tags:
    - setup


- name: Template Zabbix agent service
  template:
    src: zabbix-agent.service.j2
    dest: "{{ zabbix_agent_service_path }}"
  tags:
    - setup


- name: Start and enable Zabbix agent service
  service:
    name: "{{ zabbix_agent_service_name }}"
    state: restarted
    enabled: yes
  tags:
    - setup


- name: Stop and disable Zabbix agent service
  service:
    name: "{{ zabbix_agent_service_name }}"
    state: stopped
    enabled: no
  tags:
    - teardown


- name: Remove Zabbix agent service
  file:
    path: "{{ zabbix_agent_service_path }}"
    state: absent
  tags:
    - remove
