- name: Template Zabbix agent service
  template:
    src: zabbix-agent.service.j2
    dest: "{{ zabbix_agent_service_path }}"
    mode: 0644
  tags: [setup]

- name: Reload systemctl
  shell: |
    systemctl daemon-reload
  changed_when: false
  tags: [setup]

- name: Start and enable Zabbix agent service
  service:
    name: "{{ zabbix_agent_service_name }}"
    state: restarted
    enabled: true
  tags: [setup]

- name: Install Python requirements
  pip:
    name: "zabbix-api"
    state: present
  when:
    - zabbix_agent_server_register is true
  tags: [setup]

- name: Register host on Zabbix
  zabbix_host:
    validate_certs: false
    server_url: "{{ zabbix_agent_server_url }}"
    login_user: "{{ zabbix_agent_server_user }}"
    login_password: "{{ zabbix_agent_server_password }}"
    host_name: "{{ ansible_hostname }}"
    state: present
    status: enabled
    force: true
    description: "Managed by Ansible"
    host_groups: "{{ zabbix_agent_server_groups }}"
    link_templates: "{{ zabbix_agent_server_templates }}"
    timeout: "{{ zabbix_agent_server_timeout | int }}"
  when:
    - zabbix_agent_server_register is true
  tags: [setup]

- name: Unregister host from Zabbix
  zabbix_host:
    server_url: "{{ zabbix_agent_server_url }}"
    validate_certs: false
    login_user: "{{ zabbix_agent_server_user }}"
    login_password: "{{ zabbix_agent_server_password }}"
    host_name: "{{ ansible_hostname }}"
    state: absent
  when:
    - zabbix_agent_server_register is true
  tags: [teardown, remove]

- name: Remove Python requirements
  pip:
    name: "zabbix-api"
    state: absent
  tags: [teardown, remove]

- name: Stop and disable Zabbix agent service
  service:
    name: "{{ zabbix_agent_service_name }}"
    state: stopped
    enabled: false
  tags: [teardown, remove]

- name: Remove Zabbix agent service
  file:
    path: "{{ zabbix_agent_service_path }}"
    state: absent
  tags: [remove]
